export const API_URL = 'https://qaapi.urgentem.net';
export const TEMP_API_URL = 'https://tm-test.urgentem.net';

// --------- Auth --------------//
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const GET_PORTFOLIO_LIST_SUCCESS = 'GET_PORTFOLIO_LIST_SUCCESS';
export const GET_PORTFOLIO_LIST_FAILURE = 'GET_PORTFOLIO_LIST_FAILURE';
export const GET_PORTFOLIO_DETAILS = 'GET_PORTFOLIO_DETAILS';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_UPLOAD_PORTFOLIO_LIST_SUCCESS = 'GET_UPLOAD_PORTFOLIO_LIST_SUCCESS';
export const GET_UPLOAD_PORTFOLIO_LIST_FAILED = 'GET_UPLOAD_PORTFOLIO_LIST_FAILED';
export const UPDATE_CURRENCY_SUCCESS = 'UPDATE_CURRENCY_SUCCESS';
export const UPDATE_CURRENCY_FAILED = 'UPDATE_CURRENCY_FAILED';
export const SET_PORTFOLIO = 'SET_PORTFOLIO';
export const SET_BENCHMARK = 'SET_BENCHMARK';
export const SET_FILTER_ITEM = 'SET_FILTER_ITEM';
export const SET_TAB_SUCCESS = 'SET_TAB_SUCCESS';
export const SET_MODULE_SUCCESS = 'SET_MODULE_SUCCESS';
export const SET_FILTER_VISIBILITY = 'SET_FILTER_VISIBILITY';
export const SET_REWEIGHT_FACTOR='SET_REWEIGHT_FACTOR';
export const SET_LOADING='SET_LOADING';
export const LOGOUT_USER='LOGOUT_USER';
export const GET_DOWNLOAD_PORTFOLIOS_SUCCESS='GET_DOWNLOAD_PORTFOLIOS_SUCCESS';
export const GET_DOWNLOAD_PORTFOLIOS_FAILED='GET_DOWNLOAD_PORTFOLIOS_FAILED';
export const GET_DOWNLOAD_DETAILS_SUCCESS='GET_DOWNLOAD_DETAILS_SUCCESS';
export const GET_DOWNLOAD_DETAILS_FAILED='GET_DOWNLOAD_DETAILS_FAILED';
export const UPLOAD_PORTFOLIO_SUCCESS='UPLOAD_PORTFOLIO_SUCCESS';
export const UPLOAD_PORTFOLIO_FAILED='UPLOAD_PORTFOLIO_FAILED';
export const CHANGE_EMAIL_SUCCESS='CHANGE_EMAIL_SUCCESS';
export const SET_DOWNLOAD_PORTFOLIO='SET_DOWNLOAD_PORTFOLIO'
export const SET_DOWNLOAD_TAGS='SET_DOWNLOAD_TAGS';
export const SET_EMISSIONS_SUCCESS = 'SET_EMISSIONS_SUCCESS';
export const GET_FIX_RATE_SUCCESS = 'GET_FIX_RATE_SUCCESS'
// ---------- Footprint -----------//

export const GET_PORTFOLIO_EMISSION_SUCCESS = 'GET_PORTFOLIO_EMISSION_SUCCESS';
export const GET_PORTFOLIO_EMISSION_FAILED = 'GET_PORTFOLIO_EMISSION_FAILED';
export const GET_SOV_FOOTPRINT_SUCCESS = 'GET_SOV_FOOTPRINT_SUCCESS';
export const GET_SOV_FOOTPRINT_FAILED = 'GET_SOV_FOOTPRINT_FAILED';
export const GET_AVOIDED_EMISSIONS_SUCCESS = 'GET_AVOIDED_EMISSIONS_SUCCESS';
export const GET_AVOIDED_EMISSIONS_FAILED = 'GET_AVOIDED_EMISSIONS_FAILED';
export const GET_DISCLOSURE_SUCCESS = 'GET_DISCLOSURE_SUCCESS';
export const GET_DISCLOSURE_FAILED = 'GET_DISCLOSURE_FAILED';
export const GET_CARBON_ATTRIBUTION_SUCCESS = 'GET_CARBON_ATTRIBUTION_SUCCESS';
export const GET_CARBON_ATTRIBUTION_FAILED = 'GET_CARBON_ATTRIBUTION_FAILED';

// --------------- Scope 3 ------------//

export const GET_SCOPE3_DATA_SUCCESS = 'GET_SCOPE3_DATA_SUCCESS';
export const GET_SCOPE3_DATA_FAILED = 'GET_SCOPE3_DATA_FAILED';

// ---------------- Port Optimization -----------//

export const GET_PORTFOLIO_OPTIMIZATION_SUCCESS = 'GET_PORTFOLIO_OPTIMIZATION_SUCCESS';
export const GET_PORTFOLIO_OPTIMIZATION_FAILED = 'GET_PORTFOLIO_OPTIMIZATION_FAILED';
export const GET_PERFORMANCE_ATTRIBUTION_SUCCESS = 'GET_PERFORMANCE_ATTRIBUTION_SUCCESS';
export const GET_PERFORMANCE_ATTRIBUTION_FAILED = 'GET_PERFORMANCE_ATTRIBUTION_FAILED';

// ------------------- Risk Contributor -------------------//
export const GET_RISK_CONTRIBUTOR_SUCCESS = 'GET_RISK_CONTRIBUTOR_SUCCESS';
export const GET_RISK_CONTRIBUTOR_FAILED = 'GET_RISK_CONTRIBUTOR_FAILED';


// -------------------- Fossil Fuel ------------------------//
export const GET_FOSSIL_FUEL_DATA_SUCCESS='GET_FOSSIL_FUEL_DATA_SUCCESS';
export const GET_FOSSIL_FUEL_DATA_FAILED='GET_FOSSIL_FUEL_DATA_FAILED';
export const GET_COAL_DATA_SUCCESS='GET_COAL_DATA_SUCCESS';
export const GET_COAL_DATA_FAILED='GET_COAL_DATA_FAILED';

// ------------------- Temp Metric -----------------------//

export const GET_TEMP_SCORE_SUCCESS='GET_TEMP_SCORE_SUCCESS';
export const GET_TEMP_SCORE_FAILED='GET_TEMP_SCORE_FAILED';
export const GET_COMPANY_ANALYSIS_SUCCESS='GET_COMPANY_ANALYSIS_SUCCESS';
export const GET_COMPANY_ANALYSIS_FAILED='GET_COMPANY_ANALYSIS_FAILED';
export const GET_TEMP_ATTRIBUTION_SUCCESS='GET_TEMP_ATTRIBUTION_SUCCESS';
export const GET_TEMP_ATTRIBUTION_FAILED='GET_TEMP_ATTRIBUTION_FAILED';
export const GET_HEATMAP_SUCCESS='GET_HEATMAP_SUCCESS';
export const GET_HEATMAP_FAILED='GET_HEATMAP_FAILED';
export const GET_CONTRIB_ANALYSIS_SUCCESS='GET_CONTRIB_ANALYSIS_SUCCESS';
export const GET_CONTRIB_ANALYSIS_FAILED='GET_CONTRIB_ANALYSIS_FAILED';
export const GET_SECTORAL_TEMP_SCORE_SUCCESS = 'GET_SECTORAL_TEMP_SCORE_SUCCESS';
export const GET_SECTORAL_TEMP_SCORE_FAILED = 'GET_SECTORAL_TEMP_SCORE_FAILED';

// ------------------------- FLM ---------------------------// 
export const GET_PORTFOLIO_ALIGNMENT_SUCCESS='GET_PORTFOLIO_ALIGNMENT_SUCCESS';
export const GET_PORTFOLIO_ALIGNMENT_FAILED='GET_PORTFOLIO_ALIGNMENT_FAILED';
export const GET_TARGET_SETTING_SUCCESS='GET_TARGET_SETTING_SUCCESS';
export const GET_TARGET_SETTING_FAILED='GET_TARGET_SETTING_FAILED';
export const GET_COMPANIES_SUCCESS='GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILED='GET_COMPANIES_FAILED';
export const GET_COMPANY_PROFILE_SUCCESS='GET_COMPANY_PROFILE_SUCCESS';
export const GET_COMPANY_PROFILE_FAILED='GET_COMPANY_PROFILE_FAILED';
export const GET_CARBON_COMPANIES_SUCCESS='GET_CARBON_COMPANIES_SUCCESS';
export const GET_CARBON_COMPANIES_FAILED='GET_CARBON_COMPANIES_FAILED';
export const GET_CARBON_RETURNS_LINE_DATA_SUCCESS='GET_CARBON_RETURNS_LINE_DATA_SUCCESS';
export const GET_CARBON_RETURNS_LINE_DATA_FAILED='GET_CARBON_RETURNS_LINE_DATA_FAILED';
export const GET_CARBON_RETURNS_TABLE_DATA_SUCCESS='GET_CARBON_RETURNS_TABLE_DATA_SUCCESS';
export const GET_CARBON_RETURNS_TABLE_DATA_FAILED='GET_CARBON_RETURNS_TABLE_DATA_FAILED';