export const API_URL='https://qaapi.urgentem.net'

// --------- Auth --------------//
export const SIGNIN_USER_SUCCESS='SIGNIN_USER_SUCCESS';
export const VERIFY_USER_SUCCESS='VERIFY_USER_SUCCESS'
export const GET_PORTFOLIO_LIST_SUCCESS='GET_PORTFOLIO_LIST_SUCCESS';
export const GET_PORTFOLIO_LIST_FAILURE='GET_PORTFOLIO_LIST_FAILURE';
export const GET_PORTFOLIO_DETAILS='GET_PORTFOLIO_DETAILS';
export const GET_USER_INFO='GET_USER_INFO';
export const GET_UPLOAD_PORTFOLIO_LIST_SUCCESS='GET_UPLOAD_PORTFOLIO_LIST_SUCCESS';
export const GET_UPLOAD_PORTFOLIO_LIST_FAILED='GET_UPLOAD_PORTFOLIO_LIST_FAILED'
export const UPDATE_CURRENCY_SUCCESS='UPDATE_CURRENCY_SUCCESS';
export const UPDATE_CURRENCY_FAILED='UPDATE_CURRENCY_FAILED';
export const SET_PORTFOLIO='SET_PORTFOLIO';
export const SET_BENCHMARK='SET_BENCHMARK';
export const SET_FILTER_ITEM='SET_FILTER_ITEM';
export const SET_TAB_SUCCESS='SET_TAB_SUCCESS';
export const SET_MODULE_SUCCESS='SET_MODULE_SUCCESS';
export const SET_FILTER_VISIBILITY='SET_FILTER_VISIBILITY'


// ---------- Footprint -----------//

export const GET_PORTFOLIO_EMISSION_SUCCESS='GET_PORTFOLIO_EMISSION_SUCCESS'
export const GET_PORTFOLIO_EMISSION_FAILED='GET_PORTFOLIO_EMISSION_FAILED';
export const GET_SOV_FOOTPRINT_SUCCESS='GET_SOV_FOOTPRINT_SUCCESS';
export const GET_SOV_FOOTPRINT_FAILED='GET_SOV_FOOTPRINT_FAILED';
export const GET_AVOIDED_EMISSIONS_SUCCESS='GET_AVOIDED_EMISSIONS_SUCCESS';
export const GET_AVOIDED_EMISSIONS_FAILED='GET_AVOIDED_EMISSIONS_FAILED';
export const GET_DISCLOSURE_SUCCESS='GET_DISCLOSURE_SUCCESS';
export const GET_DISCLOSURE_FAILED='GET_DISCLOSURE_FAILED';
export const GET_CARBON_ATTRIBUTION_SUCCESS='GET_CARBON_ATTRIBUTION_SUCCESS';
export const GET_CARBON_ATTRIBUTION_FAILED='GET_CARBON_ATTRIBUTION_FAILED';


// --------------- Scope 3 ------------//

export const GET_SCOPE3_DATA_SUCCESS='GET_SCOPE3_DATA_SUCCESS';
export const GET_SCOPE3_DATA_FAILED='GET_SCOPE3_DATA_FAILED';


// ---------------- Port Optimization -----------//

export const GET_PORTFOLIO_OPTIMIZATION_SUCCESS='GET_PORTFOLIO_OPTIMIZATION_SUCCESS';
export const GET_PORTFOLIO_OPTIMIZATION_FAILED='GET_PORTFOLIO_OPTIMIZATION_FAILED';
export const GET_PERFORMANCE_ATTRIBUTION_SUCCESS='GET_PERFORMANCE_ATTRIBUTION_SUCCESS';
export const GET_PERFORMANCE_ATTRIBUTION_FAILED='GET_PERFORMANCE_ATTRIBUTION_FAILED';