export const API_URL='https://qaapi.urgentem.net'

// --------- Auth --------------//
export const SIGNIN_USER_SUCCESS='SIGNIN_USER_SUCCESS';
export const VERIFY_USER_SUCCESS='VERIFY_USER_SUCCESS'
export const GET_PORTFOLIO_LIST_SUCCESS='GET_PORTFOLIO_LIST_SUCCESS';
export const GET_PORTFOLIO_LIST_FAILURE='GET_PORTFOLIO_LIST_FAILURE';
export const GET_PORTFOLIO_DETAILS='GET_PORTFOLIO_DETAILS';
export const GET_USER_INFO='GET_USER_INFO';
export const GET_UPLOAD_PORTFOLIO_LIST_SUCCESS='GET_UPLOAD_PORTFOLIO_LIST_SUCCESS';
export const GET_UPLOAD_PORTFOLIO_LIST_FAILED='GET_UPLOAD_PORTFOLIO_LIST_FAILED'